POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbWl0YSIsImlkIjoiNjg0Y2E0NmIzZTA5NjU5NmEzN2RiZTQyIiwiaWF0IjoxNzQ5ODUzMzE1fQ.sJyb48fGYz0Gvg7MbEeI8wQiPa97EnRz0Rcbyajx8hM

{
    "title": "The one that got away",
    "author": "Ramita Khanal",
    "url": "www.blogspot.com",
    "likes": 44433433
}