POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbWl0YSIsImlkIjoiNjgzYjZhZDBkYzM5MmM5OWNkYjllYjlmIiwiaWF0IjoxNzQ4NzI0NDU2fQ.4-aziXjakAIRcZcpjvbS6qy4GCVIU5Sn6P_RiqSmx5Q

{
    "title": "The one that got away",
    "author": "Ramita Khanal",
    "url": "www.blogspot.com",
    "likes": 44433433
}